name: Test Private Runner
on:
  push:
    branches:
      - main

jobs:
  test-runner:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print Hello World
        run: echo "Hello, World!"
